apiVersion: apps/v1
kind: Deployment
metadata:
  name: pmh-rest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pmh-rest
  template:
    metadata:
      labels:
        app: pmh-rest
    spec:
      containers:
      - name: pmh-rest
        image: 194273216149.dkr.ecr.us-east-1.amazonaws.com/pmh/registry:1.0.0
        ports:
        - containerPort: 8080
