apiVersion: apps/v1
kind: Deployment
metadata:
  name: pmh-ops
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pmh-ops
  template:
    metadata:
      labels:
        app: pmh-ops
    spec:
      containers:
        - name: pmh-ops
          image: nginx:stable
          ports:
            - containerPort: 80
